include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
  errors:
    unused_import: warning # atau 'ignore' jika tidak mau melihat warning
    
linter:
  rules:
    # Non-essential untuk development
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true